### PR TITLE
Updated solutions for DOM challenge

### PR DESCRIPTION
**Pull request by rachaelcodes**
When I tried out the solutions branch for the DOM challenge, not all of them were working - so here are some updated ones.

### CODE REVIEW

**Review by ZooeyMiller — APPROVED** [review]
:tada: :sparkles:

**Review by oliverjam — CHANGES_REQUESTED** [review]
If we're removing `Object.assign` from the project notes then we probably shouldn't have it in the solution here unfortunately 😭 

I'm not sure why the initial solution using `reduce` isn't working—give me two minutes to have a look at it

**Comment by oliverjam** [comment]
Okay I figured out the problems with the original solution (and actually all the solutions from this one down). None of them actually create a function or assign the function to a variable.

```js
var functionName(param) {
...
}
```

should be
```js
var functionName = function(param) {
...
}
```

For this specific solution the reduce needs to actually return the accumulator, otherwise it doesn't do anything. Also the function needs to return the cloned state. This solution works for me:

```js
function updateStateValue(formState, inputName){
  var stateCopy = Object.keys(formState).reduce(function(accumulator, key){
    accumulator[key] = formState[key];
    return accumulator;
  }, {});
  stateCopy[inputName] = getValue(inputName);
  return stateCopy;
}
```

Would you be able to make this change and quickly fix the last few function definitions @rachaelcodes ?

**Comment by rachaelcodes** [comment]
@oliverjam how does this look?

**Comment by oliverjam** [comment]
@rachaelcodes Amazing, thank you! LGTM :shipit:

**Review by oliverjam — APPROVED** [review]

**Pull request merged**
